

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/inventory
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "8000:8000"

  celery:
    build: ./backend
    command: celery -A app.tasks worker --beat --loglevel=info
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - backend
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/inventory
      - CELERY_BROKER_URL=redis://redis:6379/0

  frontend:
     build: ./frontend
     command: npm start
     volumes:
       - ./frontend:/app
     ports:
       - "3000:3000"
     depends_on:
       - backend

volumes:
  db_data:
